apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-test
  labels:
    app: nodeapp
spec:
  replicas: 1
   scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp-deployment-test
  minReplicas: 1
  maxReplicas: 10
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver1
        image: isahaq/erpapp:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 3000
# behavior:
#   scaleDown:
#     stabilizationWindowSeconds: 300
#     policies:
#     - type: Percent
#       value: 100
#       periodSeconds: 15
#   scaleUp:
#     stabilizationWindowSeconds: 0
#     policies:
#     - type: Percent
#       value: 100
#       periodSeconds: 15
#     - type: Pods
#       value: 4
#       periodSeconds: 15
#     selectPolicy: Max
     
