apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-test-kubernetes
  labels:
    app: nodeapp-test-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-test-kubernetes
  template:
    metadata:
      labels:
        app: nodeapp-test-kubernetes 
    spec:
      containers:
      - name: nodeapp-kubernets-test
        image: isahaq/nodeapp-test:latest
        ports:
        - containerPort: 3000
