apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-kubernets-latest
  labels:
    app: nodeapp-kubernets-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-kubernets-latest
  template:
    metadata:
      labels:
        app: nodeapp-kubernets-latest 
    spec:
      containers:
      - name: nodeserver
        image: isahaq/cicdproject:203
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-kubetes-service
spec:
  selector:
    app: nodeapp-kubernets-latest 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
