apiVersion: v1
kind: Service
metadata:
  name: nodeapp-kubernetsisk-service
spec:
  selector:
    app: nodeapp-kubernets-isk 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
