apiVersion: v1
kind: Service
metadata:
  name: nodeapp-test-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
     - name: http
    targetPort: http
    nodePort: 31109
